services:
  - type: web
    name: my-web-service
    runtime: node
    plan: starter
    buildCommand: yarn; yarn build
    startCommand: yarn start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
